config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :dashboard, only: [:index]
  resources :events, only: [:create, :destroy, :new]
  resources :friendships, only: [:create, :destroy]
  resources :gym_memberships, only: [:create, :destroy]
  resources :gyms, only: [:index, :show]
  resources :logout, only: [:destroy], controller: 'sessions'
  resources :profile, only: [:edit, :show, :update], controller: 'users'
  resources :registration, only: [:new, :create], controller: 'users'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # @user_friends = FriendshipFacade.get_friends(current_user.id)
    # @user_followers = FriendshipFacade.get_followers(current_user.id)
    # @user_gyms = GymMembershipFacade.get_gym_memberships(current_user.id)
    # @user_events = EventFacade.get_events(current_user.id)
    # @past_events = EventFacade.get_events(current_user.id, 'past')
    @user_friends = current_user && current_user.id ? FriendshipFacade.get_friends(current_user.id) : []
    @user_followers = current_user && current_user.id ? FriendshipFacade.get_followers(current_user.id) : []
    @user_gyms = current_user && current_user.id ? GymMembershipFacade.get_gym_memberships(current_user.id) : []
    @user_events = current_user && current_user.id ? EventFacade.get_events(current_user.id) : []
    @past_events = if current_user && current_user.id
                     EventFacade.get_events(
                       current_user.id, 'past'
                     )
                   else
                     []
                   end
  end
end

app/views/dashboard/index.html.erb
<% if current_user %>
  <div class="container gray top-radius padding mb-1">
    <div class="row">
      <h2>My Dashboard</h2>
    </div>
  </div>

  <div class="container flex-wrap-reverse gray padding mb-1" id='profile-header'>
    <div class="row item-center center-it-all pb-3">
      <div class="col-lg">
      </div>

      <div class="col-lg">
        <img id="profile_pic" src="<%= current_user.google_image_url %>" style="width:160px; height:auto;" class='round'>

        <h1><%= current_user.full_name %></h1>

        <%= link_to 'View Profile', profile_path(current_user.id), method: :get, class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
        <%= link_to 'Edit Profile', edit_profile_path(current_user.id), method: :get, class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
      </div>

      <div class="col-lg fit-content">
        <ul class='no-bullets'>
          <li class='location'>
            <%= current_user.zip_code %>
          </li>

          <li class='goal'>
            <%= current_user.goal %>
          </li>

          <li class='calendar'>
            <%= current_user.availability %>
          </li>

          <li class='user-summary'>
            <%= current_user.summary %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3">
    <div class="row center-it-all" id='profile-nav'>
      <div class="col">
        <%= link_to "#{@user_events.size} Upcoming Workouts", '#my-upcoming-workouts', class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
      </div>

      <div class="col">
        <%= link_to "#{@user_gyms.size} Gyms", '#my-gyms', class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
      </div>

      <div class="col">
        <%= link_to "#{@user_friends.size} Following", '#my-friends', class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
      </div>

      <div class="col">
        <%= link_to "#{@user_followers.size} Followers", '#my-followers', class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
      </div>

      <div class="col">
        <%= link_to "#{@past_events.size} Completed Workouts", '#my-completed-workouts', class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
      </div>
    </div>
  </div>

  <div class="container gray top-radius padding mb-1" id='my-upcoming-workouts'>
    <div class="row">
      <h2><%= @user_events.size %> Upcoming Workouts</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3" id='upcoming-workouts'>
    <div class="row">
      <div class="d-flex flex-wrap center-it-all">
        <% if @user_events.empty? %>
          <div class='col-sm-3 card-display'>
            You have no upcoming workouts.
          </div>
        <% else %>

          <% @user_events.each do |event| %>
          <div class="col-md-3 card-display" id="event-<%= event.id%>">
            <p>
              <h5><%= event.activity %></h5>
              <div class="row center no-pad">
                <div class="fit-content no-pad">
                  <ul class='no-bullets'>
                    <li class='sign'>
                      <%= link_to event.gym_name, gym_path(event.yelp_gym_id) %>
                    </li>

                    <li class='calendar'>
                      <%= event.format_date_short %>
                    </li>

                    <li class='star'>
                      With: <%= link_to event.friend_name, profile_path(event.user_id) %>
                    </li>
                  </ul>
                </div>
              </div>

              <%= link_to 'Delete', event_path(event.id, {user_id: current_user.id, gym_membership_id: event.gym_membership_id}),
                                    method: :delete,
                                    class: "btn btn-sm btn-info button-bg btn-outline-dark",
                                    data: { confirm: 'Are you sure you want to delete this event?' } %>
            </p>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container gray top-radius padding mb-1" id='my-gyms'>
    <div class="row">
      <h2>My Gyms</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3" id='gyms'>
    <div class="row">
      <div class="d-flex flex-wrap center-it-all">
        <% if @user_gyms.empty? %>
          <div class='col-md-auto card-display'>
            You are not a member of any gym.
          </div>
        <% else %>
          <% @user_gyms.each do |gym_membership| %>
            <div class='col-xl-3 card-display' id="gym-<%= gym_membership.yelp_gym_id%>">
              <h5><%= link_to gym_membership.gym_name, gym_path(gym_membership.yelp_gym_id) %></h5>

              <div class="row center no-pad">
                <div class="fit-content no-pad">
                  <ul class='no-bullets'>
                    <li class='address'>
                      <%= gym_membership.address1 %> <br>
                      <%= gym_membership.city_state_zip %>
                    </li>
                  </ul>
                </div>
              </div>

              <%= link_to 'Remove', gym_membership_path(gym_membership.id, {user_id: current_user.id}),
                                    method: :delete,
                                    class: "btn btn-sm btn-info button-bg btn-outline-dark",
                                    data: { confirm: 'If you remove this gym, your events at this gym will also be deleted.  Are you sure you want to remove this gym?' } %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <br>

    <div class="row">
      <div align="center" id='find-gyms'>
        <%= link_to 'Find Gyms Near Me', gyms_path(zip_code: current_user.zip_code),
                                         class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
      </div>
    </div>
  </div>

  <div class="container gray top-radius padding mb-1" id='my-friends'>
    <div class="row">
      <h2><%= @user_friends.size %> Following</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3" id='friends'>
    <div class="row center-it-all">
      <% if @user_friends.empty? %>
        <div class='col-sm-3 card-display center'>
          You are not following anyone.
        </div>
      <% else %>
        <div class="row center-it-all">
          <div class="d-flex flex-wrap center-it-all">

            <% @user_friends.each do |friend| %>
              <div class='col-xl-3 card-display' id="friend-<%= friend.id%>">

                <img id="profile_pic" src="<%= friend.google_image_url %>" class='round'>

                <h5 class='mb-3'><%= link_to friend.full_name, profile_path(friend.id) %></h5>

                <div class="row center no-pad mb-3">
                  <div class="fit-content no-pad">
                    <ul class='no-bullets'>
                      <li class='location'>
                        <%= friend.zip_code %>
                      </li>

                      <li class='goal'>
                        <%= friend.goal %>
                      </li>

                      <li class='calendar'>
                        <%= friend.availability %>
                      </li>
                    </ul>
                  </div>
                </div>

                <%= link_to 'Unfollow', friendship_path(
                                        current_user.id,
                                        {
                                          user_id: current_user.id,
                                          followee_id: friend.id
                                        }),
                                        method: :delete,
                                        class: "btn btn-sm btn-info button-bg btn-outline-dark",
                                        data: { confirm: "If you unfollow this person, your events with this person will also be deleted.  Are you sure you want to unfollow this user?" } %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container gray top-radius padding mb-1" id='my-followers'>
    <div class="row">
      <h2><%= @user_followers.size %> Followers</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3" id='followers'>
    <div class="row center-it-all">
      <% if @user_followers.empty? %>
        <div class='col-sm-3 card-display center'>
          You have no followers.
        </div>
      <% else %>
        <div class="row center-it-all">
          <div class="d-flex flex-wrap center-it-all">

            <% @user_followers.each do |follower| %>
              <div class='col-xl-3 card-display' id="follower-<%= follower.id%>">

                <img id="profile_pic" src="<%= follower.google_image_url %>" class='round'>

                <h5 class='mb-3'><%= link_to follower.full_name, profile_path(follower.id) %></h5>

                <div class="row center no-pad mb-3">
                  <div class="fit-content no-pad">
                    <ul class='no-bullets'>
                      <li class='location'>
                        <%= follower.zip_code %>
                      </li>

                      <li class='goal'>
                        <%= follower.goal %>
                      </li>

                      <li class='calendar'>
                        <%= follower.availability %>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container gray top-radius padding mb-1" id='my-completed-workouts'>
    <div class="row">
      <h2><%= @past_events.size %> Completed Workouts</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3" id='completed-workouts'>
    <div class="row">
      <div class="d-flex flex-wrap center-it-all">
        <% if @past_events.empty? %>
          <div class='col-sm-3 card-display'>
            You have not completed any workouts.
          </div>
        <% else %>

          <% @past_events.each do |event| %>
          <div class="col-md-3 card-display" id="event-<%= event.id%>">
            <p>
              <h5><%= event.activity %></h5>
              <div class="row center no-pad">
                <div class="fit-content no-pad">
                  <ul class='no-bullets'>
                    <li class='sign'>
                      <%= link_to event.gym_name, gym_path(event.yelp_gym_id) %>
                    </li>

                    <li class='calendar'>
                      <%= event.format_date_short %>
                    </li>

                    <li class='star'>
                      With: <%= link_to event.friend_name, profile_path(event.user_id) %>
                    </li>
                  </ul>
                </div>
              </div>

              <%= link_to 'Delete', event_path(event.id, {user_id: current_user.id, gym_membership_id: event.gym_membership_id}),
                                    method: :delete,
                                    class: "btn btn-sm btn-info button-bg btn-outline-dark",
                                    data: { confirm: 'Are you sure you want to delete this event?' } %>
            </p>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <br><br>

<% end %>