config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :dashboard, only: [:index]
  resources :events, only: [:create, :destroy, :new]
  resources :friendships, only: [:create, :destroy]
  resources :gym_memberships, only: [:create, :destroy]
  resources :gyms, only: [:index, :show]
  resources :logout, only: [:destroy], controller: 'sessions'
  resources :profile, only: [:edit, :show, :update], controller: 'users'
  resources :registration, only: [:new, :create], controller: 'users'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def create
    UserFacade.create_user(params)
    found_user = UserFacade.get_user(params[:google_id])
    if found_user.present?
      session[:google_token] = params[:google_token]
      session[:google_id] = params[:google_id]
      redirect_to dashboard_index_path
    else
      flash[:error] = "Couldn't create your account, please try again."
      redirect_to root_path
    end
  end

  # User Profile
  def show
    # current_user_friends = FriendshipFacade.get_friends(current_user.id)
    current_user_friends = current_user && current_user.id ? FriendshipFacade.get_friends(current_user.id) : []
    return if current_user.blank?

    @profile_user = UserFacade.get_profile_user(params[:id])
    # @user_friends = FriendshipFacade.get_friends(@profile_user.id)
    # @user_followers = FriendshipFacade.get_followers(@profile_user.id)
    @user_friends = @profile_user && @profile_user.id ? FriendshipFacade.get_friends(@profile_user.id) : []
    @user_followers = @profile_user && @profile_user.id ? FriendshipFacade.get_followers(@profile_user.id) : []

    @user_type = if current_user.id.to_s == params[:id]
                   :self
                 elsif current_user_friends.any? do |friend|
                         friend.id.to_s == params[:id]
                       end
                   :friend
                 end

    return unless @user_type == :friend

    # @user_events = EventFacade.get_events(@profile_user.id)
    @user_events = @profile_user && @profile_user.id ? EventFacade.get_events(@profile_user.id) : []
  end

  def edit; end

  def update
    UserFacade.update_user(users_params, current_user.id)
    flash[:success] = 'Your profile has been updated!'
    redirect_to profile_path(current_user.id)
  end

  private

  def users_params
    params.permit(:full_name, :email, :zip_code, :summary, :goal,
                  :availability_morning, :availability_afternoon, :availability_evening)
  end
end

app/views/users/edit.html.erb
<% if current_user %>
  <div class="container gray top-radius padding mb-1">
    <div class="row">
      <h2>Edit User Profile</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding">
    <div class="row center-it-all">
      <%= form_with url: profile_path(current_user.id), method: :patch, local: true do |f| %>
        <h5><%= f.label :full_name, 'Name' %></h5>
        <%= f.text_field :full_name, value: current_user.full_name, id: :full_name, class: "form-custom center-it-all" %>

        <br><br>

        <h5><%= f.label :email, 'Email' %></h5>
        <%= f.text_field :email, value: current_user.email, readonly: true, id: :email, class: "form-custom center-it-all" %>

        <br><br>

        <h5><%= f.label :zip_code, 'Zip Code' %></h5>
        <%= f.text_field :zip_code, value: current_user.zip_code, id: :zip_code, class: "form-custom center-it-all" %>

        <br><br>

        <h5><%= f.label :summary, 'Summary' %></h5>
        <%= f.text_area :summary, value: current_user.summary, cols: 40, id: :summary, class: "form-custom center-it-all" %>

        <br><br>

        <h5><%= f.label :goal, 'Goals' %></h5>
        <%= f.select :goal, User.goals_array, value: current_user.goal, id: :goal, class: "btn btn-sm btn-white button-bg btn-outline-dark" %>

        <br><br>

        <h5><%= f.label :availability %></h5>
        <%= f.label :availability_morning, 'Morning' %>
        <%= f.check_box :availability_morning, checked: current_user.availability_morning, id: :availability_morning %>
        <br>
        <%= f.label :availability_afternoon, 'Afternoon' %>
        <%= f.check_box :availability_afternoon, checked: current_user.availability_afternoon ,id: :availability_afternoon %>
        <br>
        <%= f.label :availability_evening, 'Evening' %>
        <%= f.check_box :availability_evening, checked: current_user.availability_evening ,id: :availability_evening %>

        <br><br><br>

        <%= f.submit 'Update Profile', class: "btn btn-sm btn-white button-bg btn-outline-dark" %>
        <%= link_to 'Cancel', profile_path(current_user.id), class: "btn btn-sm btn-white button-bg btn-outline-dark"  %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container gray top-radius padding mb-1">
  <div class="row">
    <h2>Register</h2>
  </div>
</div>

<div class="container gray bottom-radius padding">
  <div class="row center-it-all">
    <%= form_with url: registration_index_path(google_id: params[:google_id], google_token: params[:google_token], google_image_url: params[:google_image_url]), local: true do |f| %>
      <h5><%= f.label :full_name, 'Name' %></h5>
      <%= f.text_field :full_name, value: params[:full_name], id: :full_name, class: "form-custom center-it-all" %>

      <br><br>

      <h5><%= f.label :email, 'Email' %></h5>
      <%= f.text_field :email, value: params[:email], readonly: true, id: :email, class: "form-custom center-it-all" %>

      <br><br>

      <h5><%= f.label :zip_code, 'Zip Code' %></h5>
      <%= f.text_field :zip_code, id: :zip_code, class: "form-custom center-it-all" %>

      <br><br>

      <h5><%= f.label :summary, 'Summary' %></h5>
      <%= f.text_area :summary, cols: 40, id: :summary, class: "form-custom center-it-all" %>

      <br><br>

      <h5><%= f.label :goal, 'Goals' %></h5>
      <%= f.select :goal, User.goals_array, include_blank: 'Select your motivation', id: :goal, class: "btn btn-sm btn-white button-bg btn-outline-dark" %>

      <br><br>

      <h5><%= f.label :availability %></h5>
      <%= f.label :availability_morning, 'Morning' %>
      <%= f.check_box :availability_morning, id: :availability_morning %>
      <br>
      <%= f.label :availability_afternoon, 'Afternoon' %>
      <%= f.check_box :availability_afternoon, id: :availability_afternoon %>
      <br>
      <%= f.label :availability_evening, 'Evening' %>
      <%= f.check_box :availability_evening, id: :availability_evening %>

      <br><br><br>

      <%= f.submit 'Register', class: "btn btn-sm btn-white button-bg btn-outline-dark" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user && @profile_user %>
  <div class="container flex-wrap-reverse gray full-radius padding mb-3">
    <div class="row item-center center-it-all" id='profile-header'>
      <div class="col-lg">
      </div>
      <div class="col-lg">
        <img id="profile_pic" src="<%= @profile_user.google_image_url %>" style="width:160px; height:auto;" class='round'>

        <h1><%= @profile_user.full_name %></h1>

        <% if @user_type == :self %>
          <%= link_to 'Edit Profile', edit_profile_path(current_user.id), class: "btn btn-med btn-info button-bg btn-outline-dark" %>
        <% elsif @user_type == :friend %>
          <%= link_to 'Unfollow', friendship_path(current_user.id,
                                                  {
                                                    user_id: current_user.id,
                                                    followee_id: @profile_user.id
                                                  }),
                                  method: :delete,
                                  class: "btn btn-sm btn-info button-bg btn-outline-dark",
                                  data: { confirm: "If you unfollow this person, your events with this person will also be deleted.  Are you sure you want to unfollow this user?" } %>
        <% else %>
          <%= link_to 'Follow', friendships_path(
                                      current_user.id,
                                      {
                                        user_id: current_user.id,
                                        followee_id: @profile_user.id
                                      }
                                    ),
                                    method: :post,
                                    class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
        <% end %>

      </div>

      <div class="col-lg fit-content">
        <ul class='no-bullets'>
          <li class= 'location' id='zip-code'>
            <%= @profile_user.zip_code %>
          </li>

          <li class='goal' id='goal'>
            <%= @profile_user.goal %>
          </li>

          <li class='calendar' id='availability'>
            <%= @profile_user.availability %>
          </li>

          <li class='user-summary' id='user-summary'>
            <%= @profile_user.summary %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <% if @user_type == :friend %>

    <div class="container gray top-radius padding mb-1">
      <div class="row">
        <h2><%= @user_events.size %> Upcoming Workouts</h2>
      </div>
    </div>

    <div class="container gray bottom-radius padding mb-3" id='upcoming-workouts'>
      <div class="row">
        <div class="d-flex flex-wrap center-it-all">
          <% if @user_events.empty? %>
            <div class='col-sm-3 card-display'>
              <%= @profile_user.full_name %> has no upcoming workouts.
            </div>
          <% else %>

            <% @user_events.each do |event| %>
            <div class="col-md-3 card-display" id="event-<%= event.id%>">
              <p>
                <h5><%= event.activity %></h5>
                <div class="row center no-pad">
                  <div class="fit-content no-pad">
                    <ul class='no-bullets'>
                      <li class='calendar'>
                        <%= event.date %>
                      </li>
                    </ul>
                  </div>
                </div>
              </p>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  <% end %>

  <div class="container gray top-radius padding mb-1">
    <div class="row">
      <h2><%= @user_friends.size %> Following</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3">
    <div class="row" id='friends'>
      <% if @user_friends.empty? %>
        <div class='col-sm-3 card-display center'>
          <%= @profile_user.full_name %> is not following anyone.
        </div>
      <% else %>
        <div class="d-flex flex-wrap center-it-all">

          <% @user_friends.each do |friend| %>
            <div class='col-xl-3 card-display' id="friend-<%= friend.id%>">

              <img id="profile_pic" src="<%= friend.google_image_url %>" class='round'>

              <h5 class='mb-3'><%= link_to friend.full_name, profile_path(friend.id) %></h5>

              <div class="row center no-pad mb-3">
                <div class="fit-content no-pad">
                  <ul class='no-bullets'>
                    <li class='location'>
                      <%= friend.zip_code %>
                    </li>

                    <li class='goal'>
                      <%= friend.goal %>
                    </li>

                    <li class='calendar'>
                      <%= friend.availability %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container gray top-radius padding mb-1" id='my-followers'>
    <div class="row">
      <h2><%= @user_followers.size %> Followers</h2>
    </div>
  </div>

  <div class="container gray bottom-radius padding mb-3" id='followers'>
    <div class="row center-it-all">
      <% if @user_followers.empty? %>
        <div class='col-sm-3 card-display center'>
          <%= @profile_user.full_name %> has no followers.
        </div>
      <% else %>
        <div class="row center-it-all">
          <div class="d-flex flex-wrap center-it-all">

            <% @user_followers.each do |follower| %>
              <div class='col-xl-3 card-display' id="follower-<%= follower.id%>">

                <img id="profile_pic" src="<%= follower.google_image_url %>" class='round'>

                <h5 class='mb-3'><%= link_to follower.full_name, profile_path(follower.id) %></h5>

                <div class="row center no-pad mb-3">
                  <div class="fit-content no-pad">
                    <ul class='no-bullets'>
                      <li class='location'>
                        <%= follower.zip_code %>
                      </li>

                      <li class='goal'>
                        <%= follower.goal %>
                      </li>

                      <li class='calendar'>
                        <%= follower.availability %>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <br><br>

<% end %>