config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :dashboard, only: [:index]
  resources :events, only: [:create, :destroy, :new]
  resources :friendships, only: [:create, :destroy]
  resources :gym_memberships, only: [:create, :destroy]
  resources :gyms, only: [:index, :show]
  resources :logout, only: [:destroy], controller: 'sessions'
  resources :profile, only: [:edit, :show, :update], controller: 'users'
  resources :registration, only: [:new, :create], controller: 'users'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">🏋️‍♂️ SpotMe 🏋️‍♂️</a>
    <button class="navbar-toggler navbar-toggler-custom" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user && session[:google_token].present? %>
          <li class="nav-item" style="padding-right:10px; padding-top:2px;">
            <%= link_to "Dashboard", dashboard_index_path, class: "btn btn-sm btn-danger button-bg btn-outline-dark" %>
          </li>
          <li class="nav-item" style="padding-right:10px; padding-top:2px;">
            <%= button_to "Find Gyms Near Me", gyms_path, method: :get, params: { zip_code: current_user.zip_code }, class: "btn btn-sm btn-danger button-bg btn-outline-dark" %>
          </li>
          <li class="nav-item" style="padding-right:10px; padding-top:2px;">
            <%= link_to "Log Out", logout_path(current_user.id), method: :delete, class: "btn btn-sm btn-danger button-bg btn-outline-dark" %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign in with Google', '/auth/google_oauth2', method: :post, class: "btn btn-sm btn-danger button-bg btn-outline-dark", id: 'sign-in' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="container flex-wrap-reverse gray center full-radius padding mb-3 mt-150" id='profile-header'>
  <div class="row item-center center-it-all">
    <h1 class='welcome-title'>Welcome to SpotMe</h1>

    <h2 class='welcome-subtitle'>
      Find your future 'SwoleMate' or fitness bestie at your gym and schedule a workout together!
    </h2>
  </div>

  <% if !current_user && session[:google_token].blank? %>
    <%= link_to 'Sign in with Google', '/auth/google_oauth2', method: :post, class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
  <% end %>
  <br><br><br>
</div>