config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :dashboard, only: [:index]
  resources :events, only: [:create, :destroy, :new]
  resources :friendships, only: [:create, :destroy]
  resources :gym_memberships, only: [:create, :destroy]
  resources :gyms, only: [:index, :show]
  resources :logout, only: [:destroy], controller: 'sessions'
  resources :profile, only: [:edit, :show, :update], controller: 'users'
  resources :registration, only: [:new, :create], controller: 'users'
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  def index
    @gyms = GymFacade.get_gyms_near_user(params[:zip_code])
  end

  def show
    @gym = GymFacade.get_gym(params[:id])
    # @user_gym_membership = GymMembershipFacade.get_gym_membership(
    #   yelp_gym_id: params[:id], user_id: current_user.id
    # )
    @user_gym_membership = if current_user && current_user.id
                             GymMembershipFacade.get_gym_membership(
                               yelp_gym_id: params[:id], user_id: current_user.id
                             )
                           end
    @gym_users_count = GymFacade.get_gym_users_count(params[:id])
    return if @user_gym_membership.blank?

    @gym_users = GymFacade.get_gym_users(params[:id])
    @gym_friends = FriendshipFacade.get_friends_at_gym(params[:id],
                                                       current_user.id)
    @gym_non_friends = FriendshipFacade.get_non_friends_at_gym(
      yelp_gym_id: params[:id], user_id: current_user.id
    )
  end
end

app/views/gyms/index.html.erb
<% if current_user %>
  <div class="container gray top-radius padding mb-1" style="width: flex;">
    <h1 class="card-title">Gyms Near My Zip Code: <%= current_user.zip_code %></h1>
  </div>

  <div class='container gray bottom-radius padding-content mb-3'>
    <div class="row" id="gyms">
      <div class="d-flex flex-wrap center-it-all">
        <% @gyms.each do |gym| %>
          <div class="col-xl-5 card-display flex-grow">
            <div id="<%= gym.yelp_gym_id %>">
              <ul class='no-bullets'>
                <li class='sign'>
                  <span class='title'><%= link_to gym.name, gym_path(gym.yelp_gym_id) %></span>
                </li>

                <li class='address'>
                  <%= gym.full_address %>
                </li>

                <% if gym.phone.present? %>
                  <li class='phone'>
                    <%= gym.phone %>
                  </li>
                <% end %>

                <li class='star'>
                  <%= gym.gym_member_count %> Active Members
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/gyms/show.html.erb
<% if current_user %>
  <div class="container flex-wrap-reverse gray full-radius padding mb-3" id='gym-details'>
    <div class="row item-center center-it-all">
      <div class="col">
        <h1><%= @gym.name %></h1>

        <div class="row center no-pad">
          <div class="fit-content no-pad">
            <ul class='no-bullets'>
              <li class='address'>
                <%= @gym.full_address %>
              </li>

              <% if @gym.phone.present? %>
                <li class='phone'>
                  <%= @gym.phone %>
                </li>
              <% end %>

              <li class='star'>
                <%= @gym_users_count.gym_member_count %> Active Members
              </li>
            </ul>
          </div>
        </div>

        <% if @user_gym_membership.present? %>
          <%= link_to 'Remove Gym', gym_membership_path(
                                      @user_gym_membership.id,
                                      { user_id: current_user.id }
                                    ),
                                    method: :delete,
                                    class: "btn btn-sm btn-white button-bg btn-outline-dark",
                                    data: { confirm: 'If you remove this gym, your events at this gym will also be deleted.  Are you sure you want to remove this gym?' } %>
        <% else %>
          <%= link_to 'Add Gym', gym_memberships_path(user_id: current_user.id,
                                                      yelp_gym_id: @gym.yelp_gym_id,
                                                      gym_name: @gym.name),
                                 method: :post,
                                 class: "btn btn-sm btn-white button-bg btn-outline-dark" %>
        <% end %>
      </div>
    </div>
  </div>

  <% if @user_gym_membership.present? %>
    <div class="container gray top-radius padding mb-1">
      <div class="row">
        <h2>Members I Follow at <%= @gym.name %></h2>
      </div>
    </div>

    <div class="container gray bottom-radius padding mb-3" id='my-friends'>
      <div class="row">
        <div class="d-flex flex-wrap center-it-all">
          <% if @gym_friends.empty? %>
            You don't follow anyone at this gym.
          <% else %>
            <% @gym_friends.each do |friend| %>
              <div class='col-xl-3 card-display' id="friend-<%= friend.id%>">

                <img id="profile_pic" src="<%= friend.google_image_url %>" class='round'>

                <h5 class='mb-3'><%= link_to friend.full_name, profile_path(friend.id) %></h5>

                <div class="row center no-pad mb-3">
                  <div class="fit-content no-pad">
                    <ul class='no-bullets'>
                      <li class='location'>
                        <%= friend.zip_code %>
                      </li>

                      <li class='goal'>
                        <%= friend.goal %>
                      </li>

                      <li class='calendar'>
                        <%= friend.availability %>
                      </li>
                    </ul>
                  </div>
                </div>

                <%= link_to 'Schedule Workout', new_event_path(
                                                friend_id: friend.id,
                                                friend_name: friend.full_name,
                                                gym_membership_id: @user_gym_membership.id,
                                                gym_name: @gym.name
                                            ),
                                            method: :get,
                                            class: "btn btn-sm btn-white button-bg btn-outline-dark" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container gray top-radius padding mb-1">
      <div class="row">
        <h2>Follow Other Members at <%= @gym.name %></h2>
      </div>
    </div>

    <div class="container gray bottom-radius padding mb-3" id='non-friends'>
      <div class="row">
        <div class="d-flex flex-wrap center-it-all">
          <% if @gym_non_friends.empty? %>
            Either you follow all the people at this gym or there are no other gym members.
          <% else %>
            <% @gym_non_friends.each do |non_friend| %>
              <div class='col-xl-3 card-display' id="non-friend-<%= non_friend.id%>">

                <img id="profile_pic" src="<%= non_friend.google_image_url %>" class='round'>

                <h5 class='mb-3'><%= link_to non_friend.full_name, profile_path(non_friend.id) %></h5>

                <div class="row center no-pad mb-3">
                  <div class="fit-content no-pad">
                    <ul class='no-bullets'>
                      <li class='location'>
                        <%= non_friend.zip_code %>
                      </li>

                      <li class='goal'>
                        <%= non_friend.goal %>
                      </li>

                      <li class='calendar'>
                        <%= non_friend.availability %>
                      </li>
                    </ul>
                  </div>
                </div>

                <%= link_to 'Follow', friendships_path(
                                            current_user.id,
                                            {
                                              user_id: current_user.id,
                                              followee_id: non_friend.id
                                            }
                                          ),
                                          method: :post,
                                          class: "btn btn-sm btn-info button-bg btn-outline-dark" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>